apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-client-deployment
  labels:
    app: hello-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-client
  template:
    metadata:
      labels:
        app: hello-client
    spec:
      containers:
      - name: hello-client
        image: freddygv/hello-client:0.1.0
      initContainers:
      - name: hello-client-init
        image: freddygv/hello-client-init:0.1.0
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
